; CreditsTextPointers indexes (see data/credits/credits_text.asm)
	const_def
	const CRED_VERSION               ; 00
	const CRED_TAJIRI                ; 01
	const CRED_OOTA                  ; 02
	const CRED_MORIMOTO              ; 03
	const CRED_WATANABE              ; 04
	const CRED_MASUDA                ; 05
	const CRED_NISHINO               ; 06
	const CRED_SUGIMORI              ; 07
	const CRED_NISHIDA               ; 08
	const CRED_MIYAMOTO              ; 09
	const CRED_KAWAGUCHI             ; 0a
	const CRED_ISHIHARA              ; 0b
	const CRED_YAMAUCHI              ; 0c
	const CRED_ZINNAI                ; 0d
	const CRED_HISHIDA               ; 0e
	const CRED_SAKAI                 ; 0f
	const CRED_YAMAGUCHI             ; 10
	const CRED_YAMAMOTO              ; 11
	const CRED_TANIGUCHI             ; 12
	const CRED_NONOMURA              ; 13
	const CRED_FUZIWARA              ; 14
	const CRED_MATSUSIMA             ; 15
	const CRED_TOMISAWA              ; 16
	const CRED_KAWAMOTO              ; 17
	const CRED_KAKEI                 ; 18
	const CRED_TSUCHIYA              ; 19
	const CRED_NAKAMURA              ; 1a
	const CRED_YUDA                  ; 1b
	const CRED_POKEMON               ; 1c
	const CRED_DIRECTOR              ; 1d
	const CRED_PROGRAMMERS           ; 1e
	const CRED_CHARACTER_DESIGN      ; 1f
	const CRED_MUSIC                 ; 20
	const CRED_SOUND_EFFECTS         ; 21
	const CRED_GAME_DESIGN           ; 22
	const CRED_MONSTER_DESIGN        ; 23
	const CRED_GAME_SCENARIO         ; 24
	const CRED_PARAMETRIC_DESIGN     ; 25
	const CRED_MAP_DESIGN            ; 26
	const CRED_TESTING               ; 27
	const CRED_SPECIAL_THANKS        ; 28
	const CRED_PRODUCER              ; 29
	const CRED_EXECUTIVE_PRODUCER    ; 2a
	const CRED_TAMADA                ; 2b
	const CRED_OOTA2                 ; 2c
	const CRED_YOSHIKAWA             ; 2d
	const CRED_OOTA23                ; 2e
	const CRED_YOSHIDA               ; 2f
	const CRED_MATSUMIYA             ; 30
	const CRED_SEYA                  ; 31
	const CRED_SEKINE                ; 32
	const CRED_SHIMAMURA             ; 33
	const CRED_SHIMOYAMADA           ; 34
	const CRED_IZUSHI                ; 35
	const CRED_HARADA                ; 36
	const CRED_SHOGAKUKAN            ; 37
	const CRED_OOTANI                ; 38
	const CRED_PIKACHU_VOICE         ; 39
	const CRED_EUROPE_STAFF          ; 3a
	const CRED_EUROPE_COORD          ; 3b
	const CRED_MOYSE                 ; 3c
	const CRED_KRAFT                 ; 3d
	const CRED_KAWAKAMI              ; 3e
	const CRED_EDASAWA               ; 3f
	const CRED_UESUGI                ; 40
	const CRED_YOSHIMURA             ; 41
	const CRED_TEXTES_ECRAN          ; 42
	const CRED_MURAKAWA              ; 43
	const CRED_FUKUI                 ; 44
	const CRED_HOSOKAWA              ; 45
	const CRED_SANO                  ; 46
	const CRED_NAKAMICHI             ; 47
	const CRED_NOE_TESTING           ; 48
	const CRED_NOA_TESTING           ; 49
	const CRED_HUDSON_BUECHELE       ; 4a
	const CRED_BARDAKOFF             ; 4b
	const CRED_FLEURY                ; 4c
	const CRED_ZEH_HEPPT             ; 4d
DEF NUM_CRED_STRINGS EQU const_value

	const_def -1, -1
	const CRED_TEXT_FADE_MON ; $FF
	const CRED_TEXT_MON      ; $FE
	const CRED_TEXT_FADE     ; $FD
	const CRED_TEXT          ; $FC
	const CRED_COPYRIGHT     ; $FB
	const CRED_THE_END       ; $FA
