; These are all the asm constants needed to make the yellow_vc patch.

; [FPA 001 Begin]
EXPORT DEF U_CHAR EQU 'U'
EXPORT DEF L_CHAR EQU 'L'
EXPORT DEF T_CHAR EQU 'T'
EXPORT DEF I_CHAR EQU 'I'
EXPORT DEF M_CHAR EQU 'M'
EXPORT DEF D_CHAR EQU 'D'
EXPORT DEF E_CHAR EQU 'E'
EXPORT DEF S_CHAR EQU 'S'
EXPORT DEF R_CHAR EQU 'R'
EXPORT DEF X_CHAR EQU 'X'
EXPORT DEF P_CHAR EQU 'P'
EXPORT DEF O_CHAR EQU 'O'
EXPORT MEGA_PUNCH

; [FPA 002 Begin]
EXPORT DEF G_CHAR EQU 'G'
EXPORT GUILLOTINE

; [FPA 003 Begin]
EXPORT MEGA_KICK

; [FPA 004 Begin]
EXPORT DEF B_CHAR EQU 'B'
EXPORT BUBBLEBEAM

; [FPA 005 Begin]
EXPORT DEF A_CHAR EQU 'A'
EXPORT HYPER_BEAM

; [FPA 006 Begin]
EXPORT DEF N_CHAR EQU 'N'
EXPORT THUNDERBOLT

; [FPA 007 Begin]
EXPORT REFLECT

; [FPA 008 Begin]
EXPORT DEF V_CHAR EQU 'V'
EXPORT DEF Z_CHAR EQU 'Z'
EXPORT DREAM_EATER
EXPORT BLIZZARD
EXPORT SPORE
EXPORT SELFDESTRUCT
EXPORT EXPLOSION

; [FPA 009 Begin]

; [FPA 010 Begin]
EXPORT ROCK_SLIDE

; [FPA 011 Begin]

; [FPA 131 Begin]

; [FPA 56 Begin]

; [FPA 40 Begin]
EXPORT DEF SPACE_CHAR EQU ' '
EXPORT HAZE